version: '3.8'

services:
  backend:
    container_name: "server"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongo
    networks:
      - crud-mongo
  mongo:
    container_name: db
    image: mongo:latest
    restart: always
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    networks:
      - crud-mongo
    # volumes:
    #   - "mongo-data:/data/db"
    expose:
      - 27017
    # command: mongod --auth
networks:
  crud-mongo:
    driver: bridge

# volumes:
#   mongo-data:
#     driver: "local"
